# Generated by Django 6.0.6 on 2026-06-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('micraje_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('micraje_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calidad de Fibra',
                'verbose_name_plural': 'Calidades de Fibra',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='NEXIS Vicuña Perú S.A.C.', max_length=150)),
                ('ruc', models.CharField(default='20601234567', max_length=20)),
                ('direccion', models.CharField(default='Av. Principal 123, Lima', max_length=250)),
                ('correo_notificaciones', models.EmailField(default='operaciones@nexis.pe', max_length=254)),
                ('telefono', models.CharField(default='+51 999 999 999', max_length=30)),
                ('moneda_base', models.CharField(default='PEN', max_length=10)),
                ('simbolo_moneda', models.CharField(default='S/', max_length=5)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=3.75, max_digits=8)),
                ('umbral_stock_bajo', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('alerta_stock_activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='EstadoProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='azul', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Procesamiento',
                'verbose_name_plural': 'Estados de Procesamiento',
                'ordering': ['nombre'],
            },
        ),
    ]
