# Generated by Django 5.2.15 on 2026-06-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={'ordering': ['provincia__nombre', 'nombre'], 'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterUniqueTogether(
            name='comunidad',
            unique_together={('provincia', 'nombre')},
        ),
    ]
