# Generated by Django 6.0.6 on 2026-06-22 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('calidad', models.CharField(max_length=30)),
                ('kg_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kg_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(default='Almacén Central', max_length=150)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('AGOTADO', 'Agotado')], default='DISPONIBLE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lote_inventario', to='compras.compra')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='zonas.region')),
            ],
            options={
                'verbose_name': 'Lote de Inventario',
                'verbose_name_plural': 'Lotes de Inventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=250)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.loteinventario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
