# Generated by Django 6.0.6 on 2026-06-22 00:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_compra', models.DateField()),
                ('kilogramos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calidad', models.CharField(choices=[('PREMIUM_A1', 'Premium A1'), ('ESTANDAR', 'Estándar'), ('CALIDAD_B', 'Calidad B')], default='ESTANDAR', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='proveedores.proveedor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='zonas.region')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
    ]
