# Generated by Django 5.2.15 on 2026-06-25 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='calidad_fibra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='configuracion.calidadfibra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='estado_procesamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='configuracion.estadoprocesamiento'),
        ),
    ]
