# Generated by Django 6.0.6 on 2026-06-22 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA_SIMULADA', 'Tarjeta simulada')], default='EFECTIVO', max_length=30)),
                ('estado', models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='PROCESADO', max_length=20)),
                ('operacion', models.CharField(blank=True, help_text='Número de operación, voucher o referencia', max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='compras.compra')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
